default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: get_help_to_retrain_development
  restricted:
    <<: *default
    database: get_help_to_retrain_restricted_development
    migrations_paths: db/restricted_migrate

test: &test
  primary:
    <<: *default
    database: get_help_to_retrain_test
  restricted:
    <<: *default
    database: get_help_to_retrain_restricted_test
    migrations_paths: db/restricted_migrate
    # Required for the azure pipelines setup
    url: <%= ENV['DATABASE_URL'] %>

production:
  primary:
    <<: *default
    host: <%= ENV['DB_HOST'] %>
    database: <%= ENV['DB_DATABASE'] %>
    username: <%= ENV['DB_USERNAME'] %>
    password: <%= ENV['DB_PASSWORD'] %>
  restricted:
    <<: *default
    host: <%= ENV['RESTRICTED_DB_HOST'] %>
    database: <%= ENV['RESTRICTED_DB_DATABASE'] %>
    username: <%= ENV['RESTRICTED_DB_USERNAME'] %>
    password: <%= ENV['RESTRICTED_DB_PASSWORD'] %>
    # Required in Heroku review apps to use the same endpoint
    # for both databases
    url: <%= ENV['RESTRICTED_DATABASE_URL'] || ENV['DATABASE_URL'] %>
    migrations_paths: db/restricted_migrate

